#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define LENGTH_OF_RACE_AND_ROLE 4
#define LENGTH_OF_THE_ARRAY_OF_OBJECTS 6
#define MAIN_MENU_LAST_POSSIBLE_CHOICE 6
#define MAIN_MENU_FIRST_POSSIBLE_CHOICE 0
#define QUEUE_LENGTH 7

// Reputation rank thresholds
#define RANK_THRESHOLD_NOVICE 0
#define RANK_THRESHOLD_ADVENTURER 50
#define RANK_THRESHOLD_GUARDIAN 100
#define RANK_THRESHOLD_VETERAN 200
#define RANK_THRESHOLD_HERO 300
#define RANK_THRESHOLD_RENOWNED_HERO 350
#define RANK_THRESHOLD_LEGEND 400

// Table column widths
#define COLUMN_WIDTH_ID 5
#define COLUMN_WIDTH_NAME 15
#define COLUMN_WIDTH_SURNAME 15
#define COLUMN_WIDTH_ROLE 15
#define COLUMN_WIDTH_LEVEL 8
#define COLUMN_WIDTH_REPUTATION 12
#define COLUMN_WIDTH_RANK 20

// Minimum values
#define MIN_REPUTATION 0
#define MIN_LEVEL 1

#endif  // CONSTANTS_H_
