#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define MAIN_MENU_LAST_POSSIBLE_CHOICE 6
#define MAIN_MENU_FIRST_POSSIBLE_CHOICE 0

// Reputation rank thresholds
#define RANK_THRESHOLD_NOVICE 0
#define RANK_THRESHOLD_ADVENTURER 50
#define RANK_THRESHOLD_GUARDIAN 100
#define RANK_THRESHOLD_VETERAN 200
#define RANK_THRESHOLD_HERO 300
#define RANK_THRESHOLD_RENOWNED_HERO 350
#define RANK_THRESHOLD_LEGEND 400

// Minimum values
#define MIN_REPUTATION 0
#define MIN_LEVEL 1

#endif  // CONSTANTS_H_
